# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

f_previous = 1
f_current = 1
sum = 0
while (f_current < 4000000):
    if(f_current%2 == 0):
        sum += f_current
    f_temp = f_previous
    f_previous = f_current
    f_current += f_temp
print sum
